[package]
name = "moonfs"
version = "0.1.0"
edition = "2024"
authors = ["Jason Phan"]
repository = "https://github.com/sudo-JP/MoonFS.git"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

